name: publish
on:
  push:
    tags:
      - v[12].[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
